// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.FaceDetector
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("faces")]
        public Face[] Faces { get; set; }

        [JsonProperty("faceCount")]
        public long FaceCount { get; set; }

        [JsonProperty("hasFaces")]
        public bool HasFaces { get; set; }

        [JsonProperty("imageWidth")]
        public long ImageWidth { get; set; }

        [JsonProperty("imageHeight")]
        public long ImageHeight { get; set; }
    }

    public partial class Face
    {
        [JsonProperty("x")]
        public long X { get; set; }

        [JsonProperty("y")]
        public long Y { get; set; }

        [JsonProperty("width")]
        public long Width { get; set; }

        [JsonProperty("height")]
        public long Height { get; set; }

        [JsonProperty("confidence")]
        public double Confidence { get; set; }
    }
}
